services:
  - type: web
    name: excel-analytics-backend
    runtime: node
    plan: free
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    region: oregon